Repository proyectos-tsdwad/integrador-modulo-fullstack, pull requests merged in 2022-10, with the labels that each got.

#19 add footer
  assets/img/logo-biblioteca.jpg
  pages/book-detail.html
  pages/books-catalog.html
  pages/contact.html
  pages/index.html
  pages/my-account.html
  style/style.css
Labels: enhancement

#31 Hot fix
  pages/index.html
  style/style.css
Labels: hot-fix

#36 Fix featured info section
  pages/contact.html
  pages/index.html
  pages/my-account.html
  pages/profile.html
  style/style.css
Labels: hot-fix

#40 add data base documentation and schema script
  documentation/data base/biblioteca DB modelo relacional.mwb
  documentation/data base/biblioteca DB schema.sql
  documentation/data base/diagrama modelo relacional.png
Labels: documentation

#41 Data base docu and script schema
  documentation/data base/biblioteca DB modelo relacional.mwb
  documentation/data base/biblioteca DB schema.sql
  documentation/data base/diagrama modelo relacional.png
Labels: documentation
